language:
  - js
env:
  - PREFIX=/usr/local
compiler:
  - clang
install:
  - nvm install 4.0.0
before_script:
  - git fetch --unshallow
script:
  - make test.js.js || ( cat tests/test.js.log ; exit 1)
  - (make minigrace.js.env && make module.test.js) || ( cat modules/tests/test.log ; exit 1 )
sudo: false
